version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - crm-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - sqlserver
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - crm-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
